msgid ""
msgstr ""
"Большой брат: Другая история\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: big-brother-as\n"
"X-Crowdin-Project-ID: 461654\n"
"X-Crowdin-Language: it\n"
"X-Crowdin-File: /master/game/tl/crowdin/options.po\n"
"X-Crowdin-File-ID: 861\n"
"Project-Id-Version: big-brother-as\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Language-Team: Italian\n"
"Language: it_IT\n"
"PO-Revision-Date: 2021-09-26 08:54\n"

msgid "Большой брат: Другая история"
msgstr "Big Brother: un'altra storia"

